### ISSUE TITLE
Gen (branch)

### ISSUE THREAD

**Issue by LegitSoulja** [LegitSoulja/jsGen-phpGen#3]
https://github.com/LegitSoulja/jsGen-phpGen/blob/Gen/README.md

**Comment by LegitSoulja** [comment]
@FantasyIsBae

**Comment by FantasyIsBae** [comment]
Yes ? :)

**Comment by FantasyIsBae** [comment]
Yay , so have u tested npm then ? :D

**Comment by LegitSoulja** [comment]
@FantasyIsBae not, I updated Gen readme.

What else should be implemented?

**Comment by LegitSoulja** [comment]
No I meant.

**Comment by FantasyIsBae** [comment]
We can work on the even and odd @LegitSoulja

**Comment by LegitSoulja** [comment]
That's easy. You can

**Comment by FantasyIsBae** [comment]
Yeah ok :)

**Comment by FantasyIsBae** [comment]
Idk if i got this:

```
				genRandomOddNumbers(length){
			var response = "";
			for(var i = 0; i < length; i++){
				response += (Math.floor(Math.random() * (0, 9) + 0 / 3));
			}
			return response;
		}

		genRandomEvenNumbers(length){
			var response = "";
			for(var i = 0; i < length; i++){
				response += (Math.floor(Math.random() * (0, 9) + 0 / 2));
			}
			return response;
		}

```

**Comment by FantasyIsBae** [comment]
@LegitSoulja

**Comment by LegitSoulja** [comment]
Nope

**Comment by FantasyIsBae** [comment]
I knew it :(

**Comment by LegitSoulja** [comment]
Lol

**Comment by FantasyIsBae** [comment]
I guess i can't do the simplest f'ing things :(

**Comment by FantasyIsBae** [comment]
Imma go swim in a puddle :(

**Comment by FantasyIsBae** [comment]
And drown in like 10 ml of water

**Comment by FantasyIsBae** [comment]
🙌 if u wanna drink milkshake 😆

**Comment by LegitSoulja** [comment]
@FantasyIsBae 
Even
```
Math.floor( Math.random() * 10 / 2 ) * 2
```

I trying to figure out odd xD

**Comment by LegitSoulja** [comment]
> Math.floor( Math.random() * 10 / 2 ) * 2

Method sucks

**Comment by FantasyIsBae** [comment]
just divide it by an odd number @LegitSoulja Right ?

**Comment by FantasyIsBae** [comment]
Im probably wrong again

**Comment by LegitSoulja** [comment]
You could do that, however it's not efficient. You'll never get a high number

**Comment by FantasyIsBae** [comment]
Yay im partially right :)

Multiply by an odd number

**Comment by LegitSoulja** [comment]
What im going to do because im lazy is create a string with odd, and even numbers

**Comment by LegitSoulja** [comment]
If you can come up with an efficient way let me know. However, Math, related functions are slow to use, as it'll take up alot of time.

**Comment by FantasyIsBae** [comment]
Ok :) 

So are we mostly sorted with odd/even numbers?

**Comment by FantasyIsBae** [comment]
Okay , will it slow the whole process down too ?

**Comment by LegitSoulja** [comment]
@FantasyIsBae read my first issue.

**Comment by FantasyIsBae** [comment]
Oh yeah , didn't think of that xD @LegitSoulja

**Comment by LegitSoulja** [comment]
@FantasyIsBae 

Odd
```
~~(Math.random()*(5-0)+0)*2+1;
```

**Comment by LegitSoulja** [comment]
Took me that long to figure it out

**Comment by FantasyIsBae** [comment]
Wow if it took you that long imagine how long it would of taken me lol @LegitSoulja

**Comment by LegitSoulja** [comment]
@FantasyIsBae but I hate math, so it'll take me a while to sit down and figure out a solution.

**Comment by LegitSoulja** [comment]
Well I wouldn't say I hate math, But I don't like to spend time with doing so :)

**Comment by FantasyIsBae** [comment]
Yea true , im not the best with math either :P

**Comment by FantasyIsBae** [comment]
You were gonna talk to me about the ban sys is that still happening ? @LegitSoulja

**Comment by LegitSoulja** [comment]
You never got the email?

**Comment by FantasyIsBae** [comment]
Nope lol

**Comment by LegitSoulja** [comment]
http://appeal.ogarul.io

But let's not discuss anything ogarul related here.

**Comment by LegitSoulja** [comment]
I'll send another email

**Comment by FantasyIsBae** [comment]
Ok thanks :)

**Comment by LegitSoulja** [comment]
Actually, the logins are different from public, and admin. You would login here http://appeal.ogarul.io/scp/login.php

And the email containing your password has been sent. If you have not received it check the spam folder.

**Comment by FantasyIsBae** [comment]
Ok i'll check

**Comment by FantasyIsBae** [comment]
Have you sent the email yet @LegitSoulja
